const EXT_TO_LANG: Record<string, string> = {
    ts: "typescript",
    tsx: "tsx",
    js: "javascript",
    jsx: "jsx",
    py: "python",
    rb: "ruby",
    go: "go",
    rs: "rust",
    java: "java",
    kt: "kotlin",
    swift: "swift",
    cs: "csharp",
    cpp: "cpp",
    c: "c",
    h: "c",
    hpp: "cpp",
    html: "html",
    css: "css",
    scss: "scss",
    less: "less",
    json: "json",
    yaml: "yaml",
    yml: "yaml",
    toml: "toml",
    md: "markdown",
    mdx: "mdx",
    xml: "xml",
    svg: "xml",
    sql: "sql",
    sh: "bash",
    bash: "bash",
    zsh: "bash",
    dockerfile: "dockerfile",
    makefile: "makefile",
    graphql: "graphql",
    prisma: "prisma",
    vue: "vue",
    svelte: "svelte",
    astro: "astro",
    mjs: "javascript",
    cjs: "javascript",
    mts: "typescript",
};

export function getLangFromPath(filePath: string): string {
    const ext = filePath.split(".").pop()?.toLowerCase() || "";
    return EXT_TO_LANG[ext] || "text";
}
